INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1,'help.supportScenario.message','en','A support scenario allows you to run all the steps of an specific test case as a single step for the current scenario. ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (2,'general.title','en','Thunder Test');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (3,'general.error.404','en','The Page you are looking for does not exist.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (4,'general.error.goBack','en','Go back to the homepage');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (5,'general.error.403','en','Access denied');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (6,'general.error.403.message','en','You do not have enough privileges to access this page.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (7,'general.error','en','Error');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (8,'general.success','en','Success');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (9,'general.pending','en','Pending');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (10,'general.text.expiredSessionTitle','en','Session expired');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (11,'general.text.expiredSessionText','en','Somebody has logged in using this account from another location');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (12,'general.youHave','en','You have');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (13,'general.messages','en','Messages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (14,'general.notifications','en','Notifications');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (15,'general.alerts','en','Alerts');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (16,'general.text.selectAll','en','Select all');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (17,'general.text.activateAll','en','Activate all');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (18,'general.text.continue','en','Continue');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (19,'general.text.save','en','Save');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (20,'general.text.update','en','Update');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (21,'general.text.reasignUser','en','Asign responsabilities');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (22,'general.text.cancel','en','Cancel');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (23,'general.text.confirmTitle','en','Are you sure?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (24,'general.text.confirmMessage','en','Are you sure you want to do this action?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (25,'general.editUser','en','Edit user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (26,'general.generalData','en','General data');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (27,'general.projectPermissions','en','Project permissions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (28,'general.grantAccess','en','Grant access');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (29,'general.grantAdminPrivileges','en','Grant admin privileges');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (30,'general.demo.info.notAllowed','en','Sorry, demo account users can not execute this action.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (31,'general.home','en','Home');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (32,'datatable.showing','en','Showing');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (33,'datatable.entries','en','Entries');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (34,'datatable.search','en','Search');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (35,'genericAction.open','en','Launch app');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (36,'genericAction.write','en','Write');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (37,'genericAction.click','en','Click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (38,'genericAction.wait','en','Wait ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (39,'genericAction.check','en','Check');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (40,'genericAction.rightClick','en','Right click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (41,'genericAction.doubleClick','en','Double click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (42,'genericAction.goBack','en','Go back');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (43,'genericAction.alert','en','Alert');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (44,'genericAction.hover','en','Hover');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (45,'genericAction.select','en','Select');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (46,'genericAction.dragAndDrop','en','Drag and drop');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (47,'genericAction.verifyValue','en','Verify value');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (48,'genericAction.elementPresent','en','Element present');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (49,'genericAction.verifyImage','en','Verify image');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (50,'genericAction.closePopup','en','Close popup');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (51,'genericAction.key','en','Key');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (52,'genericAction.ctrlKey','en','Ctrl key');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (53,'genericAction.altKey','en','Alt key');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (54,'genericAction.shiftKey','en','Shift key');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (55,'genericAction.wheelUp','en','Wheel up');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (56,'genericAction.wheelDown','en','Wheel down');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (57,'genericAction.mouseMove','en','Mouse move');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (58,'genericAction.clickCoordinates','en','Click coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (59,'genericAction.writeCoordinates','en','Write coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (60,'genericAction.copyDoubleClick','en','Copy double click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (61,'genericAction.waitForImage','en','Wait for image');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (62,'genericAction.waitForWebObject','en','Wait for web object');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (63,'genericAction.verifyURL','en','Verify URL');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (64,'fw.action.ok.open','en','Open action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (65,'fw.action.error.open','en','Error in open action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (66,'fw.action.ok.write','en','Write action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (67,'fw.action.error.write','en','Error in write action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (68,'fw.action.forceCoordinates.write','en','Write action made by coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (69,'fw.action.ok.wait','en','Wait action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (70,'fw.action.error.wait','en','Error in wait action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (71,'fw.action.error.param.wait','en','Parameter not valid for wait action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (72,'fw.action.ok.click','en','Click action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (73,'fw.action.error.click','en','Error in click action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (74,'fw.action.forceCoordinates.click','en','Click action made by coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (75,'fw.action.ok.check','en','Check action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (76,'fw.action.error.check','en','Error in check action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (77,'fw.action.error.param.check','en','Parameter not valid for check action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (78,'fw.action.forceCoordinates.check','en','Check action made by coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (79,'fw.action.ok.doubleClick','en','Double click action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (80,'fw.action.error.doubleClick','en','Error in double click action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (81,'fw.action.ok.rightClick','en',' Right click action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (82,'fw.action.error.rightClick','en','Error in right click action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (83,'fw.action.ok.goBack','en',' Go back action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (84,'fw.action.error.goBack','en','Error in go back action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (85,'fw.action.ok.alert','en','Alert action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (86,'fw.action.error.alert','en','Error in alert action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (87,'fw.action.error.param.alert','en','Parameter not valid for alert action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (88,'fw.action.ok.select','en','Select action executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (89,'fw.action.error.select','en','Error on select action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (90,'fw.action.error.param.select','en','Parameter not valid for select action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (91,'fw.exception.fileNotFound','en','Internal error (JSON not found)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (92,'fw.exception.jsonParserException','en','Internal error (JSON corrupted');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (93,'fw.exception.noBrowserFound','en','Internal error (No browser found');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (94,'fw.exception.imageNotFound','en','Internal error (Image not found');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (95,'fw.action.ok.keyCli','en','Key action on CLI executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (96,'fw.action.error.keyCli','en','Error executing key action on CLI object');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (97,'fw.action.error.param.keyCli','en','Parameter not valid for key action on CLI');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (98,'fw.action.ok.ctrPlusKey','en','Action CTRL+ executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (99,'fw.action.error.ctrPlusKey','en','Error executing CTRL+ action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (100,'fw.action.error.param.ctrPlusKey','en','Parameter not valid for CTRL+ action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (101,'fw.action.ok.altPlusKey','en','Action ALT+ executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (102,'fw.action.error.altPlusKey','en','Error executing ALT+ action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (103,'fw.action.error.param.altPlusKey','en','Parameter not valid for ALT+ action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (104,'fw.action.ok.shiftPlusKey','en','Action SHIFT+ executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (105,'fw.action.error.shiftPlusKey','en',' Error executing SHIFT+ action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (106,'fw.action.error.param.shiftPlusKey','en','Parameter not valid for SHIFT+ action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (107,'fw.action.ok.hover','en','Action hover executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (108,'fw.action.error.hover','en','Error executing hover action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (109,'fw.action.forceCoordinates.hover','en','Action hover executed using coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (110,'fw.action.ok.wheelUp','en','Action wheel up executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (111,'fw.action.error.wheelUp','en','Error executing wheel up action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (112,'fw.action.error.param.wheelUp','en','Parameter not valid for for wheel up action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (113,'fw.action.ok.wheelDown','en','Action wheel down executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (114,'fw.action.error.wheelDown','en','Error executing wheel down action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (115,'fw.action.error.param.wheelDown','en','Parameter not valid for for wheel down action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (116,'fw.action.ok.closePopup','en','Action close popup executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (117,'fw.action.error.closePopup','en','Error executing close popup action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (118,'fw.action.ok.mouseMove','en','Action mouse move executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (119,'fw.action.error.mouseMove','en','Error executing mouse move action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (120,'fw.action.error.param.mouseMove','en','Parameter not valid for mouse move action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (121,'fw.action.ok.clickXY','en','Action click coordinates executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (122,'fw.action.error.clickXY','en','Error executing click coordinates action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (123,'fw.action.error.param.clickXY','en','Parameter not valid for click coordinates action ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (124,'fw.action.ok.writeXY','en','Action write coordinates executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (125,'fw.action.error.writeXY','en','Error executing write coordinates action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (126,'fw.action.error.param.writeXY','en','Parameter not valid for write coordinates action ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (127,'fw.action.ok.copyDoubleClick','en','Action copy double click executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (128,'fw.action.error.copyDoubleClick','en','Error executing action copy double click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (129,'fw.action.error.param.copyDoubleClick','en','Parameter not valid for copy double click action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (130,'fw.action.error.waitForImage','en','Error executing action wait for image');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (131,'fw.action.ok.waitForImage','en','Action wait for image executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (132,'fw.action.error.param.waitForImage','en','Parameter not valid for wait for image action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (133,'fw.action.error.waitForWebObject','en',' Error executing action wait for web object');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (134,'fw.action.ok.waitForWebObject','en','Action wait for web object executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (135,'fw.action.error.param.waitForWebObject','en','Parameter not valid for wait for web object action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (136,'fw.action.error.verifyURL','en',' Error executing action verify URL');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (137,'fw.action.ok.verifyURL','en','Action verify URL executed successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (138,'fw.action.forceCoordinates.waitForWebObject','en','Action wait for web object executed using coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (139,'fw.exception.fileNotFound','en','Execution file not found at thunder client');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (140,'fw.exception.jsonParserException','en','Execution file corrupted');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (141,'fw.exception.noBrowserFound','en','Browsers for execution not found');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (142,'fw.exception.invalidJsonParameter','en','Execution file corrupted');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (143,'fw.exception.errorWebDriver','en','Web driver error');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (144,'fw.exception.noDriverFound','en','Browsers drivers not found');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (145,'fw.exception.invalidObjectForNatureTest','en','Web object not found');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (146,'fw.exception.invalidObjectForNatureTestChecked','en','Web object not valid for check test');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (147,'fw.exception.invalidObjectForNatureTestMultiple','en','Web object not valid for multiple select check');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (148,'fw.exception.crashFW','en','Execution framework error');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (149,'execution.overdue.deleted.target','en','The execution programmed to  <b>{0}</b>, by <b>{1}</b> in your PC has been deleted by overdue time');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (150,'execution.overdue.deleted.creator','en','The execution you programmed to  <b>{0}</b>, in the PC of <b>{1}</b> has been deleted by overdue time');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (151,'execution.error.badOpenAction','en','The action <b>launch app</b> can not have an empty value');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (152,'general.mail.subject.accountConfirmation','en','Account confirmation');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (153,'general.mail.title.accountConfirmation','en','Confirm your account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (154,'general.mail.body.accountConfirmation','en','Welcome to Thunder test, an account associated to {0} has been created. To finish the account activation process please confirm your email address by clicking the confirm account button.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (155,'general.mail.body.accountConfirmationByPass','en','Hello <b>{0}</b>, <b>{1}</b> has created a <b>Thunder test</b> account for you, to continue with the confirmation process please click on <b>confirm account button</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (156,'general.mail.button.accountConfirmation','en','Confirm account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (157,'general.mail.thunderTeam','en','The ThunderTest team');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (158,'general.mail.generated.message','en','Mail automatically generated for the account confirmation process on Thunder test.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (159,'general.mail.verifyAccountByPasswordMessage','en','Hello <b>{0}</b>, welcome to <b>Thunder test</b> please enter a password for your account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (160,'general.commercial.forgotPasswordTitle','en','Reset my password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (161,'general.commercial.forgotPasswordMessage','en','Please enter your email below and we will send you <b>a reset password link</a>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (162,'general.commercial.button.forgotPassword','en','Reset password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (163,'general.commercial.notFound.forgotPassword','en','Huh! there is none accountassociated to <b>{0}</B>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (164,'general.mail.subject.forgotPassword','en','Restore your password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (165,'general.mail.title.forgotPassword','en','Restore your password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (166,'general.mail.body.forgotPassword','en','You or somebody has request for a password restore link, below you will find a button, by clicking it you will be able to set a new password for your account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (167,'general.mail.button.forgotPassword','en','Restore my password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (168,'general.commercial.mail.forgotPassword.success','en',' We have sent an email to <b>{0}</b> please follow the instructions to restore your password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (169,'general.mail.resetPasswordMessage','en','Please enter a new password for your account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (170,'notification.objects.uploaded','en','The objects have been successfully uploaded ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (171,'commercial.navbar.home','en','Home');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (172,'commercial.navbar.features','en','Features');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (173,'commercial.navbar.demo','en','Free trial');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (174,'commercial.navbar.license','en','License');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (175,'commercial.navbar.blog','en','Blog');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (176,'commercial.navbar.contactUs','en','Contact us');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (177,'commercial.navbar.language','en','Language');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (178,'commercial.navbar.login','en','Sign in');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (179,'commercial.navbar.language.spanish','en','Spanish');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (180,'commercial.navbar.language.english','en','English');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (181,'commercial.navbar.register','en','Register');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (182,'footer.contact','en','Contact Info');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (183,'footer.address','en','Address');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (184,'footer.mobile','en','Mobile');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (185,'footer.phone','en','Phone');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (186,'footer.mailAddress','en','qmaticsupport@qvision.com.co');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (187,'text.latestTweets','en','LATEST TWEETS');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (188,'footer.titleWidget','en','What is ThunderTest ?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (189,'footer.textWidget','en','ThunderTest is a test automation tool for all types of applications.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (190,'footer.company','en','Q-Vision Technologies');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (191,'footer.about','en','About Us');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (192,'footer.support','en','Support');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (193,'footer.service','en','Services');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (194,'footer.policy','en','Privacy Policy');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (195,'login.signInNow','en','Sign in now');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (196,'login.username','en','Email');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (197,'login.password','en','Password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (198,'login.rememberMe','en','Remember me');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (199,'login.forgotPassword','en','Forgot password?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (200,'login.login','en','Sign in');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (201,'login.dontHaveAccount','en','Do not have an account yet?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (202,'login.createAccount','en','Create account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (203,'springSecurity.errors.login.fail','en','Sorry, we were not able to find a user with that username and password.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (204,'springSecurity.errors.login.expired','en','Sorry, your account has expired.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (205,'springSecurity.errors.login.passwordExpired','en','Sorry, your password has expired.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (206,'springSecurity.errors.login.disabled','en','Sorry, your account is disabled.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (207,'springSecurity.errors.login.locked','en','Looks like you have not confirmed your account, we already have sent you a mail to do it. Take care you see even in the span folder.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (208,'pricing.registerNow','en','Register now');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (209,'pricing.chooseYourPlan','en','Choose your plan');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (210,'pricing.description','en','No risks, no hidden fees, cancel whenever you want.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (211,'register.email.sent','en','An confirmation email has been sent to <b>{0}</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (212,'register.form.registerNow','en','Register  now');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (213,'register.form.personalDetails','en','Personal details');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (214,'register.form.fullname','en','Full name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (215,'register.form.phone','en','Phone');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (216,'register.form.mobile','en','Mobile');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (217,'register.form.address','en','Address');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (218,'register.form.organization','en','Organization');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (219,'register.form.accountDetails','en','Acoount details');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (220,'register.form.username','en','Email');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (221,'register.form.password','en','Password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (222,'register.form.password2','en','Confirm your password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (223,'register.form.termsTitle','en','Terms and conditions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (224,'register.form.termsMessage','en','By clicking register now you accept the <a id="termsMessage" href="#" onclick="showTermsModal(); return false;">Terms and conditions</a> of use');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (225,'register.form.offersMessage','en','I want to receive offers and information on my mail');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (226,'register.form.termsBody','en','<h4>Terms and Conditions ("Terms")</h4><p>Last updated: June 03,2016</p><p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the www.thundertest.com website (the "Service") operated by Thundertest ("us", "we", or "our").</p><p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p><p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p><p><strong>Accounts</strong></p><p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p><p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p><p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p><p><strong>Links To Other Web Sites</strong></p><p>Our Service may contain links to third-party web sites or services that are not owned or controlled by Thundertest.</p><p>Thundertest has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Thundertest shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p><p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p><p><strong>Termination</strong></p><p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p><p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p><p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p><p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.</p><p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p><p><strong>Governing Law</strong></p><p>These Terms shall be governed and construed in accordance with the laws of Colombia, without regard to its conflict of law provisions.</p><p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p><p><strong>Changes</strong></p><p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p><p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p><p><strong>Contact Us</strong></p><p>If you have any questions about these Terms, please contact us.</p>"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (227,'register.form.terms.title','en','Terms and conditions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (228,'register.form.alreadyRegistered','en','Already registered?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (229,'register.form.login','en','Sign in');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (230,'register.success.successCreateUser','en','User created successfully');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (231,'com.security.RegisterCommand.fullname.nullable.error','en','<b>Fullname</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (232,'com.security.RegisterCommand.phone.nullable.error','en','<b>Phone</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (233,'com.security.RegisterCommand.mobile.nullable.error','en','<b>Mobile</b>  is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (234,'com.security.RegisterCommand.address.nullable.error','en','<b>Address</b>  is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (235,'com.security.RegisterCommand.organization.nullable.error','en','<b>Organization</b>  is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (236,'com.security.RegisterCommand.username.nullable.error','en','You must provide an <b>email address</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (237,'com.security.RegisterCommand.username.email.error','en','You must provide a <b> valid email address</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (238,'registerCommand.username.unique','en','You must provide a <b> diferent email address, "{2}"</b> is already in use    "');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (239,'com.security.RegisterCommand.password.nullable.error','en','<b>Password</b>  is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (240,'com.security.RegisterCommand.password.error.username','en','<b>Password</b> must be diferent from email');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (241,'com.security.RegisterCommand.password.error.strength','en','<b>Password</b> must be <b>between 8 and 64 characters</b> and must contain at least <b>one Uppercase letter</b>, <b>one Lowercase letter</b> and <b>one number</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (242,'com.security.RegisterCommand.password2.nullable.error','en','<b>Password</b> confirmation is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (243,'com.security.RegisterCommand.password2.error.mismatch','en','Passwords <b>do not match</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (244,'register.error.invalidCaptcha','en','Sorry, you must check the <b>captcha</b> to register');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (245,'com.model.project.name.error.unique','en','A project named <b>{0}</b> already exist on the client scope, please choose another name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (246,'com.model.Project.name.blank.error','en',' A <b>name</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (247,'com.model.Project.description.blank.error','en','A <b>description</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (248,'com.model.page.name.error.unique','en','A page named <b>{0}</b> already exist on the client scope, please choose another name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (249,'com.model.Page.name.blank.error','en',' A <b>name</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (250,'com.model.Page.description.blank.error','en','A <b>description</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (251,'com.model.scenario.name.error.unique','en','A scenario named <b>{0}</b> already exist on the client scope, please choose another name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (252,'com.model.Scenario.name.blank.error','en',' A <b>name</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (253,'com.model.Scenario.cycle.blank.error','en','A <b>cycle</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (254,'com.model.Scenario.appVersion.blank.error','en','An <b>app version</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (255,'com.model.scenario.notDeletable.error','en','The scenario can not be deleted, because there is evidence associated to it');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (256,'navBar.help','en','Help');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (257,'navBar.languages.spanish','en','Spanish');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (258,'navBar.languages.english','en','English');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (259,'navBar.profile','en','Profile');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (260,'navBar.logout','en','Logout');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (261,'navBar.upgrade','en','Upgrade');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (262,'navbar.billing','en','Billing');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (263,'text.myUsers','en','My users');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (264,'text.addUser','en','Add user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (265,'modal.newUser.title','en','New user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (266,'modal.user.fullname','en','Fullname');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (267,'modal.user.username','en','Email');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (268,'modal.user.isAdminUser','en','Leader user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (269,'modal.button.createUser','en','Create user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (270,'com.security.User.fullname.nullable.error','en','<b>Fullname</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (271,'com.security.User.fullname.blank.error','en','<b>Fullname</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (272,'com.security.User.username.nullable.error','en','You must provide an <b>email address</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (273,'com.security.User.username.blank.error','en','You must provide an <b>email address</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (274,'com.security.User.username.email.error','en','You must provide a <b> valid email address</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (275,'user.username.unique','en','There already is a user associated to  <b>"{2}"</b>, please provide another email address"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (276,'general.text.projects','en','Projects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (277,'general.text.stage','en','Stage');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (278,'general.text.statistics','en','Statistics');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (279,'general.text.reports','en','Reports');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (280,'general.text.executions','en','Executions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (281,'text.inventory','en','Inventory');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (282,'statistic.message.projects','en','You currently have {0} associated projects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (283,'statistic.message.scenarios','en','You currently have {0} associated scenarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (284,'statistic.message.cases','en','You currently have {0} associated cases');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (285,'statistic.message.pages','en','You currently have {0} associated pages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (286,'text.browsersUsage','en','Executions by browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (287,'text.casesByBrowser','en','Executed cases by browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (288,'text.january','en','January');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (289,'text.february','en','February');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (290,'text.march','en','March');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (291,'text.april','en','April');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (292,'text.may','en','May');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (293,'text.june','en','June');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (294,'text.july','en','July');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (295,'text.august','en','August');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (296,'text.september','en','September');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (297,'text.october','en','October');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (298,'text.november','en','November');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (299,'text.december','en','December');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (300,'text.casesByMonth','en','Executed cases by month');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (301,'text.casesByUser','en','Executed cases by user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (302,'text.billingInfo','en','Account information');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (303,'text.cancelSubscription','en','Cancel subscription');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (304,'text.memberAndBilling','en','MEMBERSHIP AND BILLING');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (305,'text.password','en','Password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (306,'text.changeEmailAndPass','en','Update email and password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (307,'text.changeBillingMethod','en','Update payment method');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (308,'text.plan','en','PLAN');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (309,'text.gold','en','GOLD');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (310,'text.platinum','en','PLATINUM');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (311,'text.changePlan','en','Update plan');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (312,'text.confirmSubscriptionCancel','en','Are you sure that you want to cancel your subscription?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (313,'text.filterByCreator','en','Filter by creator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (314,'text.filterByRecName','en','Filter by record name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (315,'text.filterByType','en','Filter by object type');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (316,'text.thunderDescription','en','Traditional scenario, with selenium WEB objects, GUI objects and CLI objects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (317,'text.uftDescription','en','UFT type scenario, with UFT mapped objects, GUI objects and CLI objects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (318,'text.rftDescription','en','RFT scenario, with rational RFT objects, GUI objects and CLI objects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (319,'text.uftProjectRoute','en','Absolute path for the UFT project');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (320,'text.name','en','Name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (321,'text.referenceImage','en','	Reference image"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (322,'text.creator','en','Creator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (323,'text.recName','en','Recording name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (324,'text.createdDate','en','Creation date');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (325,'text.addToPage','en','Add to page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (326,'text.selectThePage','en','Select a page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (327,'text.project','en','Project');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (328,'text.page','en','Page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (329,'text.newPage','en','New page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (330,'text.description','en','Description');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (331,'text.privatePage','en','Private page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (332,'text.select','en','Select');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (333,'text.projects','en','Projects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (334,'text.list','en','List');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (335,'text.new','en','New');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (336,'text.successCreateProject','en','Project successfully created');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (337,'text.successEditProject','en','Project successfully edited');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (338,'text.scenarios','en','Scenarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (339,'text.pages','en','Pages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (340,'text.info','en','Information');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (341,'text.edit','en','Edit');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (342,'text.viewScenarios','en','View scenarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (343,'text.viewPages','en','View pages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (344,'text.lastUpdatedBy','en','Last updater');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (345,'text.lastUpdatedDate','en','Last update');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (346,'text.projectInfo','en','Project info');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (347,'text.typeOfPage','en','Type of page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (348,'text.objects','en','Objects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (349,'text.public','en','Public');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (350,'text.private','en','Private');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (351,'text.viewObjects','en','View objects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (352,'text.delete','en','Delete');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (353,'text.duplicatePage','en','Duplicate page');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (354,'text.pageInfo','en','Page info');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (355,'text.pageContainsUsedObjects','en','This page can not deleted because its objects are being used');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (356,'text.typeOfMap','en','Identificator type');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (357,'text.objectId','en','Object id');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (358,'text.coordinates','en','Coordninates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (359,'text.xCordinate','en','x coordinate');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (360,'text.yCordinate','en','y coordinate ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (361,'text.objectType','en','Object type');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (362,'error.object.notDeletable','en','Sorry, you can not delete this object because you are using it on steps');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (363,'error.object.notMasiveDeletable','en','Sorry, you can not delete the object <b>{0}</b> because you are using it on steps');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (364,'error.object.duplicateName','en','Sorry, there is already an object named <b>{0}</b> on this page, please choose another name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (365,'error.object.nullName','en','You must provide a name for the object');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (366,'error.object.badImageFormat','en','Sorry, we only accept png images');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (367,'error.object.nullXCoordinate','en','X coordinate is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (368,'error.object.nullYCoordinate','en','Y coordinate is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (369,'error.object.nullIdVal','en','You must provide a value for the object identificator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (370,'text.cycle','en','Cycle');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (371,'text.version','en','Version');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (372,'text.messages','en','Messages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (373,'text.steps','en','Steps');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (374,'text.cases','en','Cases');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (375,'text.execute','en','Execute');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (376,'text.viewMessages','en','View messages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (377,'text.viewSteps','en','View steps');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (378,'text.viewCases','en','View cases');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (379,'text.casePrefix','en','Case prefix');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (380,'text.browserSelection','en','Browser selection');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (381,'execution.error.notLogged','en','Sorry, you must be logged on <b>Thunder client</b> to execute');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (382,'execution.error.notCases','en','Sorry, you must have at least one enabled case to execute the scenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (383,'execution.browsers.empty','en','You must select at least one browser ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (384,'scenario.execution.direct','en','Execution successfully sent');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (385,'scenario.execution.queued','en','Execution queued');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (386,'execution.extractingData','en',"Extracting data   <i class='fa fa-spinner fa-spin'></i>")
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (387,'text.order','en','Order');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (388,'text.type','en','Type');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (389,'text.object','en','Object');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (390,'text.isEnabled','en','Enabled');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (391,'text.principalAction','en','Principal action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (392,'text.supportActions','en','Support actions ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (393,'text.notSupportActions','en','None support action has been added yet');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (394,'text.step','en','Step');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (395,'text.add','en','Add');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (396,'text.stepType','en','Type');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (397,'text.mustTakeScreenshot','en','Clue screenshot');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (398,'text.mustTakeLocalScreenshot','en','Local screenshot');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (399,'text.forceCoordinates','en','Force coordinates');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (400,'text.isMasive','en','Massive value?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (401,'text.isHidden','en','Hide step ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (402,'text.notPosibleToAddSupportAction','en','Sorry, you can just add one of each posible support action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (403,'text.message','en','Message');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (404,'text.byClueWords','en','By clue words');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (405,'text.from','en','From');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (406,'text.to','en','to');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (407,'text.scope','en','Scope');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (408,'text.all','en','All');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (409,'message.error.notDeletable','en','Sorry, you can not delete this message because it is being used on one or more scenarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (410,'text.duplicate','en','Duplicate');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (411,'text.case','en','Case');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (412,'text.extractorsAndGnerators','en','Extractors y generators');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (413,'extractor.dbExtractor','en','Database extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (414,'extractor.txtExtractor','en','Plane text extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (415,'extractor.generator','en','Data generator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (416,'extractor.dbManager','en','Database manager');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (417,'extractor.port','en','Port');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (418,'extractor.dbName','en','Database name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (419,'extractor.dbUser','en','Database user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (420,'extractor.dbPass','en','Database password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (421,'extractor.testConection','en','Test connection');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (422,'extractor.dbconection.success','en','Successfully conected');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (423,'extractor.dbconection.error','en','Unable to establish the connection');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (424,'extractor.dbConection.error.notLogged','en','You must be logged on Thunder Client to test a database connection');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (425,'extractor.extratorName','en','Extractor name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (426,'extractor.query','en','Query');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (427,'extractor.fieldMap','en','Fields map');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (428,'extractor.dbField','en','Db column name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (429,'extractor.txtField','en','File column number');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (430,'extractor.clueField','en','Clue column');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (431,'extractor.placeholder.document','en','ID');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (432,'extractor.file','en','File');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (433,'extractor.delimiter','en','Delimiter');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (434,'extractor.generatorName','en','Name Generator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (435,'extractor.generatorType','en','Type of generator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (436,'extractor.generatorTypeString','en','Alphanumeric');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (437,'extractor.generatorTypeNumeric','en','Numeric');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (438,'extractor.generatorTypeFormat','en','By Format');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (439,'extractor.generatorLength','en','Length');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (440,'extractor.generatorCompound','en','Compound');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (441,'extractor.generatorLength','en','Length');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (442,'extractor.generatorPattern','en','Pattern');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (443,'extractor.generatorRangeInit','en','Range Initial');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (444,'extractor.generatorRangeEnd','en','Range End');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (445,'extractor.txtExtractor.notExist','en','There is no associated text extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (446,'extractor.scenario.notExist','en','There is no scenario associated');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (447,'extractor.file.error','en','You must load a plain text file');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (448,'extractor.file.notPlain','en','Malformed must be plain text file');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (449,'extractor.name.blank','en','You must give a name to this extraction');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (450,'extractor.name.duplicate','en','Text extractor already exists with the same name');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (451,'extractor.delimiter.blank','en','You must enter a text delimiter');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (452,'extractor.cases.error','en','Data entered in cases are incorrect');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (453,'extractor.file.empty','en','The file is empty');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (454,'extractor.objects.empty','en','No special order or destination of the data');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (455,'text.notCases','en','None case has been added yet');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (456,'com.model.Case.description.blank.error','en','A description is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (457,'com.model.Case.description.nullable.error','en','A description is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (458,'com.model.BDExtractor.name.blank.error','en','You must assign a <b>name</b> to the extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (459,'com.model.BDExtractor.name.duplicate.error','en','There is already an extractor called <b>"{0}"</b> associated to this scenario, please choose another name"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (460,'com.model.BDExtractor.bdName.blank.error','en','The <b>database name</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (461,'com.model.BDExtractor.dbUser.blank.error','en','The <b>database user</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (462,'com.model.BDExtractor.port.blank.error','en','You must specify the <b>port</b> for the database connection');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (463,'com.model.BDExtractor.query.blank.error','en','You can not create an extractor from an empty <b>query</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (464,'com.model.BDExtractor.ip.blank.error','en','You must provide an <b>ip</b> to the database connection');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (465,'com.model.BDExtractor.fieldsMap.blank.error','en','The <b>fields map</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (466,'com.model.BDExtractor.cases.blank.error','en','You must specify which <b>cases</b> is the extractor valid for');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (467,'com.model.BDExtractor.clueField.blank.error','en','The <b>clue field</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (468,'com.model.Generator.name.duplicate.error','en','There is already an generator called <b>"{0}"</b> associated to this scenario, please choose another name"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (469,'com.model.Generator.name.blank.error','en','You must assign a <b>name</b> to the generator');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (470,'com.model.Generator.fieldsMap.blank.error','en','The <b>fields map</b> is required');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (471,'com.model.Generator.cases.blank.error','en','You must specify which <b>cases</b> is the generator valid for');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (472,'generator.length.blank.error','en','The <b>length</b> field can not be empty');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (473,'generator.pattern.blank.error','en','The <b>pattern</b> field can not be empty');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (474,'generator.range.blank.error','en','The <b>Range Initial</b> and <b>Range End</b> field can not be empty');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (475,'generator.range.less.error','en','The <b>Initial Range</b> field can not be higher at the <b>End Range</b> field');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (476,'text.executionDate','en','Execution date');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (477,'text.executor','en','Executor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (478,'text.target','en','Execution host');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (479,'text.scenario','en','Scenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (480,'text.progress','en','Progress');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (481,'execution.type','en','Execution type');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (482,'execution.oneTime','en','Once');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (483,'execution.specificDays','en','Specific days');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (484,'execution.daily','en','Daily');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (485,'execution.execDays','en','Execution days');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (486,'execution.monday','en','Monday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (487,'execution.tuesday','en','Tuesday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (488,'execution.wednesday','en','Wednesday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (489,'execution.thursday','en','Thursday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (490,'execution.friday','en','Friday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (491,'execution.saturday','en','Saturday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (492,'execution.sunday','en','Sunday');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (493,'execution.cases.example','en','E.g. 1,2,3... or 1-5');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (494,'execution.initDate','en','Initial date');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (495,'execution.create','en','Schedule execution');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (496,'execution.create.success','en','Successfully scheduled execution');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (497,'execution.waitingDate','en','Waiting execution date');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (498,'text.programmedExecutions','en','Programmed executions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (499,'text.browsers','en','Browsers');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (500,'text.callingFW','en','Starting frame-work');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (501,'text.running','en','Executing');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (502,'text.savingLogs','en','Saving logs');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (503,'log.executeLog','en','Execution Log');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (504,'log.stage','en','State');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (505,'log.cycle','en','Cycle');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (506,'log.version','en','Version');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (507,'log.casesNumber','en','Number of Cases');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (508,'log.failCases','en','Failed Cases');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (509,'log.duration','en','Duration');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (510,'log.dateExecution','en','Execution Date');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (511,'log.host','en','Execution Host');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (512,'log.executor','en','Executor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (513,'log.viewDetails','en','View Details');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (514,'log.executeCases','en','Executed Test Cases');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (515,'log.testCase','en','Test Case');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (516,'log.browser','en','Browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (517,'log.stepCount','en','Number of Steps');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (518,'log.executedSteps','en','Executed Steps');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (519,'log.object','en','Object');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (520,'log.action','en','Action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (521,'log.message','en','Message');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (522,'log.state','en','State');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (523,'log.image','en','Image');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (524,'log.details','en','Details');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (525,'log.filterByProject','en','Filter by project');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (526,'log.filterByScenario','en','Filter by scenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (527,'log.stepNumber','en','Step number');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (528,'text.profile','en','Profile');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (529,'text.changeAvatar','en','Change avatar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (530,'text.changePassword','en','Change password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (531,'text.actualPass','en','Please enter your current password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (532,'text.newPass','en','Please enter your new password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (533,'text.confirmPass','en','Please confirm your new password');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (534,'error.password2.error.mismatch','en','Sorry, the passwords <b>do not match </b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (535,'error.password.notCurrent','en','Sorry, that is <b>not your current password</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (536,'error.password.error.username','en','Your password <b>can not be your email</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (537,'error.password.error.strength','en','<b>Password</b> must be <b>between 8 and 64 characters</b> and must contain at least <b>one Uppercase letter</b>, <b>one Lowercase letter</b> and <b>one number</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (538,'password.successfullyChanged','en','Password successfully changed');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (539,'mapper.pressKeys','en','Press <b>SHIFT+R</b> or click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (540,'mapper.toOpenMapper','en','to open the mapper');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (541,'tooltip.upgrade.title','en','Upgrade');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (542,'tooltip.upgrade.text','en','Upgrade your demo license to a premiun or gold license and unblock features.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (543,'tooltip.help.title','en','Help');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (544,'tooltip.help.text','en','Here you can find videos and tutorials that will help you to use correctly thundertest');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (545,'tooltip.executions.title','en','Executions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (546,'tooltip.executions.text','en','Here you will find the current executions and those that you have programmed');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (547,'tooltip.messages.title','en','Messages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (548,'tooltip.notifications.title','en','Notifications');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (549,'tooltip.alerts.title','en','Alerts');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (550,'tooltip.stage.title','en','Stage');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (551,'tooltip.stage.text','en','Stage is the area where your mapped objects are after the mapping action');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (552,'tooltip.projects.title','en','Projects');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (553,'tooltip.projects.text','en','The projects associated to your account');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (554,'tooltip.reports.title','en','Reports');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (555,'tooltip.reports.text','en','Evidences of the executions associated to your project');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (556,'tooltip.myUsers.title','en','My users');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (557,'tooltip.myUsers.text','en','Users associated to you by the license owner');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (558,'tooltip.inventory.title','en','Inventory');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (559,'tooltip.inventory.text','en','This is the inventory of your account, how many projects, scenarios, cases and pages');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (560,'tooltip.projectsWeather.text','en','Weather of your projects, more sunny more successfull executions');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (561,'tooltip.casesVsBrowser.title','en','Executed cases by browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (562,'tooltip.casesVsBrowser.text','en','How many cases you have executed in each browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (563,'tooltip.executionsVsBrowser.title','en','Executions by browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (564,'tooltip.executionsVsBrowser.text','en','Pie view of the executions done by browser');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (565,'tooltip.executionsVsMonth.title','en','Executions by month');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (566,'tooltip.executionsVsMonth.text','en','How many executions have been done on each month of the current year');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (567,'tooltip.casesVsUser.title','en','Cases executed by user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (568,'tooltip.casesVsUser.text','en','How many cases have executed each user');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (569,'tooltip.downloadIntaller.text','en','Download thunder client');
