INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (570,'help.supportScenario.message','es','Un scenario de soporte te permite ejecutar todos los pasos, de un caso especifico de un escenario diferente al actual, como un unico paso asi no tendrás que escribir los mimos pasos de otro escenario para poder ejecutar.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (571,'general.title','es','Thunder Test');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (572,'general.error.goBack','es','Volver a la página principal');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (573,'general.error.404','es','La página que estás buscando no existe');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (574,'general.error.403','es','Acceso restringido');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (575,'general.error.403.message','es','No tienes permiso para acceder a esta página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (576,'general.error','es','Error');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (577,'general.success','es','Exitoso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (578,'general.pending','es','Pendiente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (579,'general.text.expiredSessionTitle','es','Sesión expirada');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (580,'general.text.expiredSessionText','es','Alguien mas ha ingresado al sistema usando esta cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (581,'general.youHave','es','Tienes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (582,'general.messages','es','Mensajes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (583,'general.notifications','es','Notificaciones');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (584,'general.alerts','es','Alertas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (585,'general.text.selectAll','es','Seleccionar todo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (586,'general.text.activateAll','es','Activar todo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (587,'general.text.continue','es','Continuar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (588,'general.text.save','es','Guardar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (589,'general.text.update','es','Actualizar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (590,'general.text.reasignUser','es','Asignar responsabilidades');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (591,'general.text.cancel','es','Cancelar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (592,'general.text.confirmTitle','es','¿Estás seguro?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (593,'general.text.confirmMessage','es','¿Estás seguro que quieres realizar esta acción?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (594,'general.editUser','es','Editar usuario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (595,'general.generalData','es','Datos generales');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (596,'general.projectPermissions','es','Acceso a proyectos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (597,'general.grantAccess','es','Dar acceso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (598,'general.grantAdminPrivileges','es','Dar privilegios de usuario administrador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (599,'general.demo.info.notAllowed','es','Lo siento, los usuarios de cuenta demo no tienen acceso a esta funcionalidad');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (600,'general.home','es','Inicio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (601,'datatable.showing','es','Mostrando');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (602,'datatable.entries','es','Elementos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (603,'datatable.search','es','Buscar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (604,'genericAction.open','es','Abrir app');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (605,'genericAction.write','es','Escribir');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (606,'genericAction.click','es','Click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (607,'genericAction.wait','es','Esperar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (608,'genericAction.check','es','Check');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (609,'genericAction.rightClick','es','Click derecho');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (610,'genericAction.doubleClick','es','Doble click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (611,'genericAction.goBack','es','Atras');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (612,'genericAction.alert','es','Alerta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (613,'genericAction.hover','es','Hover');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (614,'genericAction.select','es','Seleccionar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (615,'genericAction.dragAndDrop','es','Deslizar y soltar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (616,'genericAction.verifyValue','es','Verificar valor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (617,'genericAction.elementPresent','es','Elemento presente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (618,'genericAction.verifyImage','es','Verificar imagen');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (619,'genericAction.closePopup','es','Cerrar popup');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (620,'genericAction.key','es','Tecla');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (621,'genericAction.ctrlKey','es','Tecla Ctrl');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (622,'genericAction.altKey','es','Tecla Alt');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (623,'genericAction.shiftKey','es','Tecla shift');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (624,'genericAction.wheelUp','es','Scroll arriba');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (625,'genericAction.wheelDown','es','Scroll abajo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (626,'genericAction.mouseMove','es','Mover mouse');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (627,'genericAction.clickCoordinates','es','Click por coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (628,'genericAction.writeCoordinates','es','Escribir por coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (629,'genericAction.copyDoubleClick','es','Doble click, copiar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (630,'genericAction.waitForImage','es','Esperar por imagen');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (631,'genericAction.waitForWebObject','es','Esperar por objeto web');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (632,'genericAction.verifyURL','es','Verificar URL');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (633,'fw.action.ok.open','es','Acción abrir app ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (634,'fw.action.error.open','es','Error en la accion abrir app');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (635,'fw.action.ok.write','es','Acción escribir ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (636,'fw.action.error.write','es','Error en la acción escribir ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (637,'fw.action.forceCoordinates.write','es','Acción escribir ejecutada mediante coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (638,'fw.action.ok.click','es','Acción click ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (639,'fw.action.error.click','es','Error en la acción click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (640,'fw.action.forceCoordinates.click','es','Acción click ejecutada mediante coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (641,'fw.action.ok.wait','es','Acción esperar ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (642,'fw.action.error.wait','es','Error en la acción esperar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (643,'fw.action.error.param.wait','es','Parámetro no válido para la acción esperar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (644,'fw.action.ok.check','es','Acción check ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (645,'fw.action.error.check','es','Error en la acción check');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (646,'fw.action.error.param.check','es','Parámetro no válido para la acción check');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (647,'fw.action.forceCoordinates.check','es','Acción check ejecutada por coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (648,'fw.action.ok.doubleClick','es','Acción doble click ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (649,'fw.action.error.doubleClick','es','Error en la acción doble click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (650,'fw.action.ok.rightClick','es','Acción click derecho ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (651,'fw.action.error.rightClick','es','Error en la acción click derecho');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (652,'fw.action.ok.goBack','es','Acción ir atras ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (653,'fw.action.error.goBack','es','Error en la acción ir atras');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (654,'fw.action.ok.alert','es','Acción alerta ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (655,'fw.action.error.alert','es','Error en la acción alerta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (656,'fw.action.error.param.alert','es','Parametro no válido para la acción alerta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (657,'fw.action.ok.select','es','Acción select ejecutada exitosamente ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (658,'fw.action.error.select','es','Error en la acción select');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (659,'fw.action.error.param.select','es','Parametro no válido para la acción select');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (660,'fw.exception.fileNotFound','es','Internal error (JSON not found)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (661,'fw.exception.jsonParserException','es','Internal error (JSON corrupted)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (662,'fw.exception.noBrowserFound','es','Internal error (No browser found)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (663,'fw.exception.imageNotFound','es','Internal error (Image not found)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (664,'fw.action.ok.keyCli','es','Acción tecla sobre CLI ejecutada exitosamente (CLI)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (665,'fw.action.error.keyCli','es','Error al ejecutar la acción tecla sobre CLI');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (666,'fw.action.error.param.keyCli','es','Parametro no válido para la acción tecla sobre CLI');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (667,'fw.action.ok.ctrPlusKey','es','Acción CTRL+ ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (668,'fw.action.error.ctrPlusKey','es','Error al ejecutar la acción CTRL+');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (669,'fw.action.error.param.ctrPlusKey','es','Parametro no válido para la acción CTRL+');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (670,'fw.action.ok.altPlusKey','es','Acción ALT+ ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (671,'fw.action.error.altPlusKey','es','Error al ejecutar la acción ALT+');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (672,'fw.action.error.param.altPlusKey','es','Parametro no válido para la acción ALT+');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (673,'fw.action.ok.shiftPlusKey','es','Acción SHIFT+ ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (674,'fw.action.error.shiftPlusKey','es','Error al ejecutar la acción SHIFT+');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (675,'fw.action.error.param.shiftPlusKey','es','Parametro no válido para la acción SHIFT+');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (676,'fw.action.ok.hover','es','Acción hover ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (677,'fw.action.error.hover','es','Error al ejecutar la acción hover');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (678,'fw.action.forceCoordinates.hover','es','Acción hover ejecutada por coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (679,'fw.action.ok.wheelUp','es','Acción rueda arriba ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (680,'fw.action.error.wheelUp','es','Error al ejecutar la acción rueda arriba');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (681,'fw.action.error.param.wheelUp','es','Parámetro no válido para la acción rueda arriba');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (682,'fw.action.ok.wheelDown','es','Acción rueda abajo ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (683,'fw.action.error.wheelDown','es','Error al ejecutar la acción rueda abajo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (684,'fw.action.error.param.wheelDown','es','Parámetro no válido para la acción rueda abajo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (685,'fw.action.ok.closePopup','es','Acción cerrar popup ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (686,'fw.action.error.closePopup','es','Error al ejecutar la accion cerrar popup');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (687,'fw.action.ok.mouseMove','es','Acción mover mouse ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (688,'fw.action.error.mouseMove','es','Error al ejecutar accion mover mouse');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (689,'fw.action.error.param.mouseMove','es','Parámetro no válido para la acción mover mouse');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (690,'fw.action.ok.clickXY','es','Acción click coordenadas ejecutada exitosmente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (691,'fw.action.error.clickXY','es','Error al ejecutar la acción click coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (692,'fw.action.error.param.clickXY','es','Parámetro no válido para la acción click coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (693,'fw.action.ok.writekXY','es','Acción escribir coordenadas ejecutada exitosmente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (694,'fw.action.error.writekXY','es','Error al ejecutar la acción escribir coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (695,'fw.action.error.param.writeXY','es','Parámetro no válido para la acción escribir coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (696,'fw.action.ok.copyDoubleClick','es','Acción copiar doble click ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (697,'fw.action.error.copyDoubleClick','es','Error al ejecutar la acción copiar doble click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (698,'fw.action.error.param.copyDoubleClick','es','Parámetro no válido para la acción copiar doble click');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (699,'fw.action.error.waitForImage','es','Error al ejecutar la acción esperar por imagen');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (700,'fw.action.ok.waitForImage','es','Acción esperar por imagen ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (701,'fw.action.error.param.waitForImage','es','Parametro no válido para la acción esperar por imagen');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (702,'fw.action.error.waitForWebObject','es','Error al ejecutar la acción esperar por objeto web');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (703,'fw.action.ok.waitForWebObject','es','Acción esperar por objeto web ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (704,'fw.action.error.param.waitForWebObject','es','Parametro no válido para la acción esperar por objeto web');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (705,'fw.action.error.verifyURL','es','Error al ejecutar la acción verificar URL');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (706,'fw.action.ok.verifyURL','es','Acción verificar URL ejecutada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (707,'fw.action.forceCoordinates.waitForWebObject','es','Acción esperar por objeto web ejecutada mediante coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (708,'fw.exception.fileNotFound','es','Archivo de ejecución no encontrado en thunder client');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (709,'fw.exception.jsonParserException','es','Archivo de ejecución corrupto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (710,'fw.Exception.noBrowserFound','es','Navegadores de ejecución no encontrados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (711,'fw.exception.invalidJsonParameter','es','Archivo de ejecución corrupto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (712,'fw.exception.errorWebDriver','es','Error en el web driver');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (713,'fw.exception.noDriverFound','es','Drivers para navegadores no encontrados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (714,'fw.exception.invalidObjectForNatureTest','es','Objeto web no encontrado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (715,'fw.exception.invalidObjectForNatureTestChecked','es','Objeto web no válido para pruebas de checkbox');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (716,'fw.exception.invalidObjectForNatureTestMultiple','es','Objeto web no válido para pruebas de select multiple');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (717,'fw.exception.crashFW','es','Error en el framework de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (718,'execution.overdue.deleted.target','es','La ejecución programada para  <b>{0}</b>, por <b>{1}</b> en tu PC ha sido eliminada porque se sobrepasó la hora de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (719,'execution.overdue.deleted.creator','es','La ejecución que progamaste para  <b>{0}</b>, en el PC de <b>{1}</b> ha sido eliminada porque se sobrepasó la hora de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (720,'execution.error.badOpenAction','es','La acción <b>Abrir app</b> no puede tener un valor vacío');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (721,'general.mail.subject.accountConfirmation','es','Confirmación de cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (722,'general.mail.title.accountConfirmation','es','Confirma tu cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (723,'general.mail.body.accountConfirmationByPass','es','Hola <b>{0}</b>, <b>{1}</b> ha creado una cuenta en <b>Thunder test</b> para ti, para continuar con el proceso debes dar click en <b>confirmar cuenta</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (724,'general.mail.body.accountConfirmation','es','Bienvenido  a Thunder test, se ha creado una cuenta a nombre de {0}. Para finalizar el proceso de registro por favor confirma tu dirección de correo electrónico dando click en el boton confirmar cuenta.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (725,'general.mail.button.accountConfirmation','es','Confirmar cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (726,'general.mail.thunderTeam','es','El equipo de Thundertest');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (727,'general.mail.generated.message','es','Correo electrónico autogenerado para el proceso de confirmación de cuenta en Thunder test.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (728,'general.mail.verifyAccountByPasswordMessage','es','Hola <b>{0}</b>, bienvenido a <b>Thunder test</b>  por favor ingresa una contraseña para tu cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (729,'general.commercial.forgotPasswordTitle','es','Restablecer mi contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (730,'general.commercial.forgotPasswordMessage','es','Ingresa tu correo electrónico y te enviaremos un <b>enlace</b> para que puedas restablecer tu contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (731,'general.commercial.button.forgotPassword','es','Restablecer contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (732,'general.commercial.notFound.forgotPassword','es','Lo siento, no se encontró ninguna cuenta asociada a <b>{0}</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (733,'general.mail.subject.forgotPassword','es','Restablecer contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (734,'general.mail.title.forgotPassword','es','Restablece tu contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (735,'general.mail.body.forgotPassword','es','Solicitaste restablecer tu contraseña, así que te enviamos este correo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (736,'general.mail.button.forgotPassword','es','Restablecer contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (737,'general.commercial.mail.forgotPassword.success','es','Hemos enviado un correo electrónico a <b>{0}</b> sigue las instrucciones para restablecer tu contraseña.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (738,'general.mail.resetPasswordMessage','es','Por favor ingresa una nueva contraseña para tu cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (739,'notification.objects.uploaded','es','Los objetos se han subido correctamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (740,'commercial.navbar.home','es','Inicio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (741,'commercial.navbar.features','es','Características');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (742,'commercial.navbar.demo','es','Prueba gratuita');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (743,'commercial.navbar.license','es','Licencia');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (744,'commercial.navbar.blog','es','Blog');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (745,'commercial.navbar.contactUs','es','Contáctenos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (746,'commercial.navbar.language','es','Idioma');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (747,'commercial.navbar.login','es','Entrar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (748,'commercial.navbar.language.spanish','es','Español');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (749,'commercial.navbar.language.english','es','Ingles');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (750,'commercial.navbar.register','es','Registrarme');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (751,'footer.contact','es','Información de Contacto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (752,'footer.address','es','Dirección');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (753,'footer.mobile','es','Celular');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (754,'footer.phone','es','Telefono');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (755,'footer.mailAddress','es','qmaticsupport@qvision.com.co');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (756,'text.latestTweets','es','TWEETS RECIENTES');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (757,'footer.titleWidget','es','¿Qué es ThunderTest?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (758,'footer.textWidget','es','ThunderTest es una herramienta de automatización de pruebas para todo tipo de aplicaciones.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (759,'footer.company','es','Q-Vision Technologies');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (760,'footer.about','es','Acerca de nosotros');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (761,'footer.support','es','Soporte');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (762,'footer.service','es','Servicios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (763,'footer.policy','es','Politicas de Privacidad');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (764,'login.signInNow','es','Ingresar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (765,'login.username','es','Correo electrónico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (766,'login.password','es','Contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (767,'login.rememberMe','es','Recordarme');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (768,'login.forgotPassword','es','¿Olvidaste tu contraseña?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (769,'login.login','es','Entrar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (770,'login.dontHaveAccount','es','¿No estás registrado?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (771,'login.createAccount','es','Crear cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (772,'springSecurity.errors.login.fail','es','Lo siento, no se encontró ninguna cuenta con ese email y contraseña.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (773,'springSecurity.errors.login.expired','es','Lo siento, tu cuenta ha expirado.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (774,'springSecurity.errors.login.passwordExpired','es','Lo siento, tu password ha expirado.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (775,'springSecurity.errors.login.disabled','es','Lo siento, tu cuenta está deshabilitada.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (776,'springSecurity.errors.login.locked','es','Antes de seguir debes <b>confirmar tu cuenta</b>, revisa tu correo electrónico ya te hemos enviado un mensaje para que lo hagas, debes revisar incluso en la carpeta de spam.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (777,'pricing.registerNow','es','Registrarme');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (778,'pricing.chooseYourPlan','es','Escoge tu plan');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (779,'pricing.description','es','Sin riesgos, sin cuotas ocultas, cancelas cuando quieras.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (780,'register.email.sent','es','Un correo de confirmación ha sido enviado a <b>{0}</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (781,'register.form.registerNow','es','Registrarme');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (782,'register.form.personalDetails','es','Detalles personales');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (783,'register.form.fullname','es','Nombre completo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (784,'register.form.phone','es','Teléfono');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (785,'register.form.mobile','es','Celular');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (786,'register.form.address','es','Dirección');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (787,'register.form.organization','es','Organización');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (788,'register.form.accountDetails','es','Detalles de acceso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (789,'register.form.username','es','Correo electrónico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (790,'register.form.password','es','Contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (791,'register.form.password2','es','Confirma tu contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (792,'register.form.termsTitle','es','Términos y condiciones');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (793,'register.form.termsMessage','es','"showTermsModal(); return false;>Términos y condiciones</a> de uso de la herramienta"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (794,'register.form.offersMessage','es','Quiero recibir ofertas en mi correo electrónico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (795,'register.form.termsBody','es','"<h4> Términos y condiciones ( ""Términos"") </h4> <p> Última actualización: 03 de junio de, el año 2016 </p> <p> Por favor, lea estos términos y condiciones ( ""Términos"", ""Términos y Condiciones"") cuidadosamente antes de usar el sitio web www.thundertest.com (el ""Servicio"") operado por Thundertest ( ""nosotros"", ""nos"" o ""nuestro""). </p> <p> Su acceso y uso del Servicio está condicionada a la aceptación y cumplimiento de estas condiciones. Estos términos se aplican a todos los visitantes, usuarios y otras personas que accedan o usen el servicio. </p> <p> Al acceder o utilizar el Servicio usted acepta que quedará vinculado por estas Condiciones. Si no está de acuerdo con alguna parte de los términos, entonces no puede tener acceso al servicio. </p> <p> <strong> Cuentas </strong> </p> <p> Cuando se crea una cuenta con nosotros, debe proporcionar la información que sea precisa, completa y actualizada en todo momento. De no hacerlo constituye un incumplimiento de las condiciones, lo que puede resultar en la terminación inmediata de su cuenta en nuestro servicio. </p> <p> Usted es responsable de salvaguardar la contraseña que utiliza para acceder al Servicio y para cualquier actividad o acciones bajo su contraseña, si su contraseña es con nuestro servicio o un servicio de terceros. </p> <p> Usted se compromete a no revelar su contraseña a terceros. Nos debe notificar inmediatamente al darse cuenta de cualquier violación de seguridad o uso no autorizado de su cuenta. </p> <p> <strong> Enlaces a otros sitios web </strong> </p> <p> Nuestro Servicio puede contener enlaces a sitios web de terceros o servicios que no son propiedad o están controladas por Thundertest. </ p> <p> Thundertest no tiene control sobre, y no asume ninguna responsabilidad por el contenido, las políticas de privacidad o prácticas de cualquier web de terceros sitios o servicios. Además, usted reconoce y acepta que Thundertest no será responsable o estará obligado, directa o indirectamente, por cualquier daño o pérdida causada o supuestamente causada por o en conexión con el uso o la credibilidad en cualquier Contenido, bienes o servicios disponibles en o a través de cualquiera de tales sitios web o servicios. </p> <p> Le recomendamos que lea los términos y condiciones y las políticas de privacidad de los sitios web de terceros o servicios que usted visita. </ p> <p> <strong> Terminación </strong> </ p> <p> Podemos cancelar o suspender el acceso a nuestro servicio de inmediato, sin previo aviso o responsabilidad, por cualquier motivo, incluyendo, sin limitación, si usted no cumple con las condiciones. </p> <p> Todas las disposiciones de las condiciones que por su naturaleza deberían sobrevivir a la terminación sobrevivirán a la terminación, incluyendo, sin limitación, las disposiciones de propiedad, renuncias de garantía, indemnización y limitaciones de responsabilidad. </p> <p> Podemos cancelar o suspender su cuenta inmediatamente, sin previo aviso o responsabilidad, por cualquier motivo, incluyendo, sin limitación, si usted no cumple con las condiciones. </p> <p> Si desea cancelar su cuenta, usted puede simplemente dejar de utilizar el servicio. </p> <p> Todas las disposiciones de las condiciones que por su naturaleza deberían sobrevivir a la terminación sobrevivirán a la terminación, incluyendo, sin limitación, las disposiciones de propiedad, renuncias de garantía, indemnización y limitaciones de responsabilidad. </p> <p> <strong> Ley de Administración </strong> </p> <p> Estos Términos se regirán e interpretarán de acuerdo con las leyes de Colombia, sin tener en cuenta su conflicto de provisiones de la ley. </p> <p> Nuestra incapacidad para hacer cumplir cualquier derecho o disposición de estas Condiciones no serán considerados una renuncia a esos derechos. Si alguna disposición de estas Condiciones se considera inválida o inaplicable por un tribunal, las restantes disposiciones de estas Condiciones permanecerán en vigor. Estos Términos y Condiciones constituyen el acuerdo completo entre nosotros con respecto a nuestro servicio, y anula y sustituye cualquier acuerdo anterior que podríamos tener entre nosotros en relación con el Servicio. </p> <p> <strong> Cambios </strong> </p> <p> Nos reservamos el derecho, a nuestra sola discreción, de modificar o sustituir estas Condiciones en cualquier momento. Si la revisión es el material vamos a tratar de proporcionar por lo menos 30 días de antelación antes de los nuevos términos que surtan efecto. Lo que constituye un cambio material será determinado a nuestra discreción. </p> <p> Al continuar para acceder o utilizar nuestro servicio después de esas revisiones se hacen efectivos, usted acepta que quedará vinculado por los términos revisados. Si no acepta los nuevos términos, por favor, deje de utilizar el servicio. </p> <p> <strong> Contacto </strong> </p> <p> Si usted tiene alguna pregunta acerca de estos Términos, por favor, póngase en contacto con nosotros. </p>"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (796,'register.form.terms.title','es','Términos y condiciones');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (797,'register.form.alreadyRegistered','es','¿Ya tienes una cuenta?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (798,'register.form.login','es','Entrar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (799,'register.success.successCreateUser','es','Usuario creado exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (800,'com.security.RegisterCommand.fullname.nullable.error','es','El campo <b>nombre</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (801,'com.security.RegisterCommand.phone.nullable.error','es','El campo <b>teléfono</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (802,'com.security.RegisterCommand.mobile.nullable.error','es','El campo <b>celular</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (803,'com.security.RegisterCommand.address.nullable.error','es','El campo <b>dirección</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (804,'com.security.RegisterCommand.organization.nullable.error','es','El campo <b>organización</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (805,'com.security.RegisterCommand.username.nullable.error','es','Debes ingresar una dirección de <b>correo electrónico</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (806,'com.security.RegisterCommand.username.email.error','es','La dirección de correo <b> no es válida</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (807,'registerCommand.username.unique','es','"Ya existe un usuario asociado a  <b>""{2}""</b>, por favor escoge otra dirección de correo"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (808,'com.security.RegisterCommand.password.nullable.error','es','<b>La contraseña</b> es obligatoria');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (809,'com.security.RegisterCommand.password.error.username','es','<b>La contraseña</b> debe ser diferente del correo electrónico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (810,'com.security.RegisterCommand.password.error.strength','es','<b>La contraseña</b> debe tener <b>entre 8 y 64 caracteres</b> y debe incluir como mínimo <b>una letra mayúscula</b>, <b>una letra minúscula</b> y <b>un número</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (811,'com.security.RegisterCommand.password2.nullable.error','es','La <b>confirmación de contraseña</b> es requerida');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (812,'com.security.RegisterCommand.password2.error.mismatch','es','Las contraseñas <b>no coinciden</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (813,'register.error.invalidCaptcha','es','Lo siento, debes completar exitosamente el <b>captcha</b> para registrarte');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (814,'com.model.project.name.error.unique','es','Ya existe un proyecto llamado <b>{0}</b> por favor escoge otro nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (815,'com.model.Project.name.blank.error','es','Debes ingresar un <b>nombre</b> para el proyecto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (816,'com.model.Project.description.blank.error','es','Debes ingresar una <b>descripción</b> para el proyecto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (817,'com.model.page.name.error.unique','es','Ya existe una página llamada <b>{0}</b> por favor escoge otro nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (818,'com.model.Page.name.blank.error','es','Debes ingresar un <b>nombre</b> para la página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (819,'com.model.Page.description.blank.error','es','Debes ingresar una <b>descripción</b> para la página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (820,'com.model.scenario.name.error.unique','es','Ya existe un escenario llamado <b>{0}</b> por favor escoge otro nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (821,'com.model.Scenario.name.blank.error','es','Debes ingresar un <b>nombre</b> para el escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (822,'com.model.Scenario.cycle.blank.error','es','Debes indicar el <b>ciclo</b> para el escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (823,'com.model.Scenario.appVersion.blank.error','es','Debes ingresar <b>version de aplicación</b> para el escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (824,'com.model.scenario.notDeletable.error','es','No se puede eliminar el escenario porque existen evidencias asociadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (825,'navBar.upgrade','es','Comprar licencia');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (826,'navBar.help','es','Ayuda');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (827,'navBar.languages.spanish','es','Español');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (828,'navBar.languages.english','es','Ingles');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (829,'navBar.profile','es','Perfil');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (830,'navBar.logout','es','Salir');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (831,'navbar.billing','es','Facturación');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (832,'text.myUsers','es','Mis usuarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (833,'text.addUser','es','Agregar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (834,'modal.newUser.title','es','Nuevo usuario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (835,'modal.user.fullname','es','Nombre completo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (836,'modal.user.username','es','Correo electrónico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (837,'modal.user.isAdminUser','es','Usuario líder');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (838,'modal.button.createUser','es','Crear usuario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (839,'com.security.User.fullname.nullable.error','es','El campo <b>nombre</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (840,'com.security.User.fullname.blank.error','es','El campo <b>nombre</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (841,'com.security.User.username.nullable.error','es','Debes ingresar una dirección de <b>correo electrónico</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (842,'com.security.User.username.blank.error','es','Debes ingresar una dirección de <b>correo electrónico</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (843,'com.security.User.username.email.error','es','La dirección de correo <b> no es válida</b> ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (844,'user.username.unique','es','"Ya existe un usuario asociado a  <b>""{2}""</b>, por favor escoge otra dirección de correo"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (845,'general.text.projects','es','Proyectos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (846,'general.text.stage','es','Intercambio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (847,'general.text.statistics','es','Estadísticas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (848,'general.text.reports','es','Reportes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (849,'general.text.executions','es','Ejecuciones');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (850,'text.inventory','es','Inventario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (851,'statistic.message.projects','es','Actualmente tienes {0} proyectos asociados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (852,'statistic.message.scenarios','es','Actualmente tienes {0} escenarios asociados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (853,'statistic.message.cases','es','Actualmente tienes {0} casos asociados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (854,'statistic.message.pages','es','Actualmente tienes {0} páginas asociadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (855,'text.browsersUsage','es','Ejecuciones por navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (856,'text.casesByBrowser','es','Casos ejecutados por navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (857,'text.january','es','Enero');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (858,'text.february','es','Febrero');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (859,'text.march','es','Marzo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (860,'text.april','es','Abril');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (861,'text.may','es','Mayo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (862,'text.june','es','Junio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (863,'text.july','es','Julio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (864,'text.august','es','Agosto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (865,'text.september','es','Septiembre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (866,'text.october','es','Octubre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (867,'text.november','es','Noviembre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (868,'text.december','es','Diciembre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (869,'text.casesByMonth','es','Casos ejecutados por mes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (870,'text.casesByUser','es','Casos ejecutados por usuario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (871,'text.billingInfo','es','Información de la cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (872,'text.cancelSubscription','es','Cancelar subscripción');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (873,'text.memberAndBilling','es','TITULAR Y MEDIO DE PAGO');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (874,'text.password','es','Contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (875,'text.changeEmailAndPass','es','Cambiar correo y contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (876,'text.changeBillingMethod','es','Cambiar método de pago');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (877,'text.plan','es','PLAN');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (878,'text.gold','es','GOLD');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (879,'text.platinum','es','PLATINUM');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (880,'text.changePlan','es','Cambiar plan');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (881,'text.confirmSubscriptionCancel','es','¿Está seguro que quieres cancelar la subscripción?');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (882,'text.filterByCreator','es','Filtrar por creador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (883,'text.filterByRecName','es','Filtrar por nombre de grabación');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (884,'text.filterByType','es','Filtrar por tipo de objeto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (885,'text.thunderDescription','es','Escenario tradicional, con objetos WEB selenium, objetos GUI y objetos CLI');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (886,'text.uftDescription','es','Escenario de tipo UFT, con objetos web tipo UFT, objetos GUI y objetos CLI');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (887,'text.rftDescription','es','Escenario de tipo RFT, con objetos web tipo rational RFT, objetos GUI y objetos CLI');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (888,'text.uftProjectRoute','es','Ruta absoluta del proyecto UFT');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (889,'text.name','es','Nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (890,'text.referenceImage','es','Imágen de referencia');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (891,'text.creator','es','Creador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (892,'text.recName','es','Nombre de grabación');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (893,'text.createdDate','es','Fecha de creación ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (894,'text.addToPage','es','Agregar a la página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (895,'text.selectThePage','es','Selecciona una página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (896,'text.project','es','Proyecto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (897,'text.page','es','Página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (898,'text.newPage','es','Nueva página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (899,'text.description','es','Descripción');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (900,'text.privatePage','es','Página privada');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (901,'text.select','es','Seleccionar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (902,'text.projects','es','Proyectos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (903,'text.list','es','Lista');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (904,'text.new','es','Nuevo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (905,'text.successCreateProject','es','Poyecto creado exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (906,'text.successEditProject','es','Proyecto editado exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (907,'text.scenarios','es','Escenarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (908,'text.pages','es','Páginas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (909,'text.info','es','Información');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (910,'text.edit','es','Editar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (911,'text.viewScenarios','es','Ver escenarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (912,'text.viewPages','es','Ver páginas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (913,'text.lastUpdatedBy','es','Ultimo en actualizar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (914,'text.lastUpdatedDate','es','Ultima actualización');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (915,'text.projectInfo','es','Información de proyecto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (916,'text.typeOfPage','es','Tipo de página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (917,'text.objects','es','Objetos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (918,'text.public','es','Pública');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (919,'text.private','es','Privada ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (920,'text.viewObjects','es','Ver objetos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (921,'text.delete','es','Borrar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (922,'text.duplicatePage','es','Duplicar página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (923,'text.pageInfo','es','Información de la página');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (924,'text.pageContainsUsedObjects','es','Esta página no puede ser borrada porque los objectos se estan utilizando');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (925,'text.typeOfMap','es','Tipo de identificador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (926,'text.objectId','es','Id de objeto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (927,'text.coordinates','es','Coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (928,'text.xCordinate','es','Coordenada x');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (929,'text.yCordinate','es','Coordenada y ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (930,'text.objectType','es','Tipo de objeto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (931,'error.object.notDeletable','es','Lo siento, no puedes eliminar este objeto porque lo estás usando en algun paso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (932,'error.object.notMasiveDeletable','es','Lo siento, no puedes eliminar el objeto <b>{0}</b> porque lo estás usando en algun paso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (933,'error.object.duplicateName','es','Lo siento, ya existe un objeto llamado <b>{0}</b> en esta página, por favor escoge otro nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (934,'error.object.nullName','es','No puedes crear un objeto si no le asignas un nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (935,'error.object.badImageFormat','es','Solo se aceptan imagenes en formato png');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (936,'error.object.nullXCoordinate','es','La coordenada x es requerida');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (937,'error.object.nullYCoordinate','es','La coordenada y es requerida');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (938,'error.object.nullIdVal','es','Debes introducir un valor para el identificador del objeto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (939,'text.cycle','es','Ciclo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (940,'text.version','es','Versión');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (941,'text.messages','es','Mensajes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (942,'text.steps','es','Guión');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (943,'text.cases','es','Casos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (944,'text.execute','es','Ejecutar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (945,'text.viewMessages','es','Ver mensajes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (946,'text.viewSteps','es','Ver guión');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (947,'text.viewCases','es','Ver casos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (948,'text.casePrefix','es','Prefijo de caso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (949,'text.browserSelection','es','Selección de navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (950,'execution.error.notLogged','es','Lo siento, debes estar conectado desde <b>Thunder client</b> para ejecutar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (951,'execution.error.notCases','es','Lo siento, debes tener al menos un caso activo para ejecutar el escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (952,'execution.browsers.empty','es','Debes escoger por lo menos un navegador ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (953,'scenario.execution.direct','es','Ejecución envíada con éxito');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (954,'scenario.execution.queued','es','Ejecución encolada');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (955,'execution.extractingData','es',''fa fa-spinner fa-spin'></i>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (956,'text.order','es','Orden');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (957,'text.type','es','Tipo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (958,'text.object','es','Objeto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (959,'text.isEnabled','es','Activo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (960,'text.principalAction','es','Acción principal');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (961,'text.supportActions','es','Acciones de soporte ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (962,'text.notSupportActions','es','No se han agregado acciones de soporte');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (963,'text.step','es','Paso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (964,'text.add','es','Agregar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (965,'text.stepType','es','Tipo de paso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (966,'text.mustTakeScreenshot','es','Captura de pantalla (clave)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (967,'text.mustTakeLocalScreenshot','es','Captura de pantalla (local)');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (968,'text.forceCoordinates','es','Forzar coordenadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (969,'text.isMasive','es','Valor masivo ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (970,'text.isHidden','es','Ocultar paso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (971,'text.notPosibleToAddSupportAction','es','Lo siento, no puedes agregar dos acciones de soporte iguales ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (972,'text.message','es','Mensaje');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (973,'text.byClueWords','es','Palabras clave');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (974,'text.from','es','Desde');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (975,'text.to','es','a');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (976,'text.scope','es','Rango');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (977,'text.all','es','Todos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (978,'message.error.notDeletable','es','Lo siento, no es posible eliminar el mensaje porque está siendo usado en algun escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (979,'text.duplicate','es','Duplicar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (980,'text.case','es','Caso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (981,'text.extractorsAndGnerators','es','Extractores y generadores');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (982,'extractor.dbExtractor','es','Extractor base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (983,'extractor.txtExtractor','es','Extractor de texto plano');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (984,'extractor.generator','es','Generador de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (985,'extractor.dbManager','es','Gestor de base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (986,'extractor.port','es','Puerto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (987,'extractor.dbName','es','Nombre de la base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (988,'extractor.dbUser','es','Usuario de la base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (989,'extractor.dbPass','es','Contraseña de la base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (990,'extractor.testConection','es','Probar conexión');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (991,'extractor.dbconection.success','es','Conexión exitosa');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (992,'extractor.dbconection.error','es','Imposible conectarse');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (993,'extractor.dbConection.error.notLogged','es','Debes conectarte desde <b>Thunder Client</b> para probar una conexión de base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (994,'extractor.extratorName','es','Nombre del extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (995,'extractor.query','es','Consulta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (996,'extractor.fieldMap','es','Mapa de campos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (997,'extractor.dbField','es','Columna base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (998,'extractor.txtField','es','# Columna del archivo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (999,'extractor.clueField','es','Campo clave');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1000,'extractor.placeholder.document','es','Cédula');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1001,'extractor.file','es','Archivo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1002,'extractor.delimiter','es','Delimitador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1003,'extractor.generatorName','es','Nombre del Generador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1004,'extractor.generatorType','es','Tipo de Generación');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1005,'extractor.generatorTypeString','es','Alfanúmerico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1006,'extractor.generatorTypeNumeric','es','Númerico');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1007,'extractor.generatorTypeFormat','es','Por formato');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1008,'extractor.generatorLength','es','Longitud');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1009,'extractor.generatorCompound','es','Compuesto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1010,'extractor.generatorLength','es','Longitud');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1011,'extractor.generatorPattern','es','Patrón');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1012,'extractor.generatorRangeInit','es','Rango Inicial');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1013,'extractor.generatorRangeEnd','es','Rango Final');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1014,'extractor.txtExtractor.notExist','es','No existe el extractor de texto asociado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1015,'extractor.scenario.notExist','es','No existe el escenario asociado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1016,'extractor.file.error','es','Debes cargar un archivo de texto plano');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1017,'extractor.file.notPlain','es','Formato incorrecto, debe ser archivo de texto plano');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1018,'extractor.name.blank','es','Debes darle un nombre a esta extraccion');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1019,'extractor.name.duplicate','es','Ya existe un extractor de texto con este mismo nombre');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1020,'extractor.delimiter.blank','es','Debes ingresar un delimitador de texto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1021,'extractor.cases.error','es','Los datos ingresados en casos son incorrectos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1022,'extractor.file.empty','es','El archivo se encuentra vacio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1023,'extractor.objects.empty','es','No se ha seleccionado el orden o destino de los datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1024,'text.notCases','es','No se ha agregado ningún caso aún');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1025,'com.model.Case.description.blank.error','es','Es necesaria la descripción');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1026,'com.model.Case.description.nullable.error','es','Es necesaria la descripción');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1027,'com.model.BDExtractor.name.blank.error','es','Debes darle un <b>nombre</b> al extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1028,'com.model.BDExtractor.name.duplicate.error','es','"Ya existe un extractor llamado <b>""{0}""</b> asociado a este escenario, debes escoger otro nombre"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1029,'com.model.BDExtractor.bdName.blank.error','es','El <b>nombre de la base de datos</b> es obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1030,'com.model.BDExtractor.dbUser.blank.error','es','El <b>usuario de la base de datos</b> es un campo obligatorio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1031,'com.model.BDExtractor.port.blank.error','es','Debes especificar el <b>puerto</b> de conexión a la base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1032,'com.model.BDExtractor.query.blank.error','es','No se puede crear un extractor a partir de una <b>consulta</b> vacía');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1033,'com.model.BDExtractor.ip.blank.error','es','Debes especificar la <b>ip</b> de conexión a la base de datos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1034,'com.model.BDExtractor.fieldsMap.blank.error','es','Es necesario especificar el <b>mapa de campos</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1035,'com.model.BDExtractor.cases.blank.error','es','Debes especificar los <b>casos</b> para los cuales es válido este extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1036,'com.model.BDExtractor.clueField.blank.error','es','El <b>campo clave</b> es obligatorio para la creación del extractor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1037,'com.model.Generator.name.duplicate.error','es','"Ya existe un Generador llamado <b>""{0}""</b> asociado a este escenario, debes escoger otro nombre"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1038,'com.model.Generator.name.blank.error','es','Debes darle un <b>nombre</b> al generador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1039,'com.model.Generator.fieldsMap.blank.error','es','Es necesario especificar el <b>mapa de campos</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1040,'com.model.Generator.cases.blank.error','es','Debes especificar los <b>casos</b> para los cuales es válido este generador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1041,'generator.length.blank.error','es','Debes darle una valor al campo <b>longitud</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1042,'generator.pattern.blank.error','es','Debes darle una valor al campo <b>Patrón</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1043,'generator.range.blank.error','es','Los campos <b>Rango Inicial</b> y <b>Rango Final</b> no pueden estar vacios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1044,'generator.range.less.error','es','El campo <b>Rango Inicial</b> no puede ser mayor al campo <b>Rango Final</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1045,'text.executionDate','es','Fecha de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1046,'text.executor','es','Ejecutor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1047,'text.target','es','Host de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1048,'text.scenario','es','Escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1049,'text.progress','es','Progreso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1050,'execution.type','es','Tipo de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1051,'execution.oneTime','es','Una vez');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1052,'execution.specificDays','es','Días especificos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1053,'execution.daily','es','Diariamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1054,'execution.execDays','es','Días de ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1055,'execution.monday','es','Lunes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1056,'execution.tuesday','es','Martes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1057,'execution.wednesday','es','Miércoles');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1058,'execution.thursday','es','Jueves');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1059,'execution.friday','es','Viernes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1060,'execution.saturday','es','Sabado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1061,'execution.sunday','es','Domingo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1062,'execution.cases.example','es','E.g. 1,'2,'3... ó 1-5');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1063,'execution.initDate','es','Fecha inicial');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1064,'execution.create','es','Agendar ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1065,'execution.create.success','es','Ejecución programada exitosamente');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1066,'execution.waitingDate','es','Esperando Fecha de Ejecución');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1067,'text.programmedExecutions','es','Ejecuciones programadas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1068,'text.browsers','es','Navegadores');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1069,'text.callingFW','es','Iniciando framework');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1070,'text.running','es','Ejecutando');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1071,'text.savingLogs','es','Guardando evidencias');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1072,'log.executeLog','es','Logs de Ejecucion');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1073,'log.stage','es','Escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1074,'log.cycle','es','Ciclo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1075,'log.version','es','version');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1076,'log.casesNumber','es','Numero de Casos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1077,'log.failCases','es','Casos Fallidos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1078,'log.duration','es','Duracíon');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1079,'log.dateExecution','es','Fecha de Ejecucion');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1080,'log.host','es','Host de Ejecucíon');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1081,'log.executor','es','Ejecutor');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1082,'log.viewDetails','es','Ver Detalles');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1083,'log.executeCases','es','Casos Ejecutados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1084,'log.testCase','es','Caso de Prueba');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1085,'log.browser','es','Navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1086,'log.stepCount','es','Número de Pasos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1087,'log.executedSteps','es','Pasos Ejecutados');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1088,'log.object','es','Objeto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1089,'log.action','es','Acción');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1090,'log.message','es','Mensaje');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1091,'log.state','es','Estado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1092,'log.image','es','Imagen');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1093,'log.details','es','Detalles');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1094,'log.filterByProject','es','Filtrar por proyecto');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1095,'log.filterByScenario','es','Filtrar por escenario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1096,'log.stepNumber','es','Número de paso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1097,'text.profile','es','Perfil');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1098,'text.changeAvatar','es','Cambiar avatar');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1099,'text.changePassword','es','Cambiar contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1100,'text.actualPass','es','Ingresa tu contraseña actual');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1101,'text.newPass','es','Ingresa la nueva contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1102,'text.confirmPass','es','Confirma la nueva contraseña');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1103,'error.password2.error.mismatch','es','Las contraseñas <b>no coinciden</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1104,'error.password.notCurrent','es','Error, la contraseña ingresada no es la <b>actual</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1105,'error.password.error.username','es','La <b>contraseña</b> no puede coincidir con tu <b>correo electrónico</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1106,'error.password.error.strength','es','<b>La contraseña</b> debe tener <b>entre 8 y 64 caracteres</b> y debe incluir como mínimo <b>una letra mayúscula</b>, <b>una letra minúscula</b> y <b>un número</b>');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1107,'password.successfullyChanged','es','Se ha cambiado la contrraseña correctamente ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1108,'mapper.pressKeys','es','Presiona <b>SHIFT+R</b> o da click en ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1109,'mapper.toOpenMapper','es','para abrir el mapeador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1110,'tooltip.upgrade.title','es','Dejar de ser demo');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1111,'tooltip.upgrade.text','es','Adquiere una licencia gold o platino y disfruta de las características que no están disponibles en la versión demo.');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1112,'tooltip.help.title','es','Ayuda');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1113,'tooltip.help.text','es','Aquí encontrarás vídeos y tutoriales que te ayudarán a usar de manera correcta y eficiente thundertest');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1114,'tooltip.executions.title','es','Ejecuciones');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1115,'tooltip.executions.text','es','Aquí encontrarás las ejecuciones que se están realizando en este momento y las que has programado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1116,'tooltip.messages.title','es','Mensajes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1117,'tooltip.notifications.title','es','Notificaciones');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1118,'tooltip.alerts.title','es','Alertas');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1119,'tooltip.stage.title','es','Intercambio');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1120,'tooltip.stage.text','es','Intercambio es el área donde encuentras los objetos que has mapeado');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1121,'tooltip.projects.title','es','Proyectos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1122,'tooltip.projects.text','es','Los proyectos asociados a tu cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1123,'tooltip.reports.title','es','Reportes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1124,'tooltip.reports.text','es','Evidencias de ejecuciones asociadas a tus proyectos');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1125,'tooltip.myUsers.title','es','Mis usuarios');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1126,'tooltip.myUsers.text','es','Usuarios asociados a ti por el dueño de la licencia ');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1127,'tooltip.inventory.title','es','Inventario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1128,'tooltip.inventory.text','es','"Este es el inventario de tu cuenta, cuantos proyectos, escenarios, casos y páginas has creado"');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1129,'tooltip.projectsWeather.text','es','Clima de los proyectos, cuanto mas soleado mas ejecuciones exitosas se han hecho');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1130,'tooltip.casesVsBrowser.title','es','Casos ejecutados por navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1131,'tooltip.casesVsBrowser.text','es','Cuantos casos han sido ejecutados en cada navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1132,'tooltip.executionsVsBrowser.title','es','Ejecuciones por navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1133,'tooltip.executionsVsBrowser.text','es','Gráfico de pastel que muestra las ejecuciones hechas por cada navegador');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1134,'tooltip.executionsVsMonth.title','es','Casos ejecutados por mes');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1135,'tooltip.executionsVsMonth.text','es','Cuantas ejecuciones has hecho en cada mes del año en curso');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1136,'tooltip.casesVsUser.title','es','Casos ejecutados por usuario');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1137,'tooltip.casesVsUser.text','es','Muestra cuantos casos han sido ejecutados por cada usuario asociado a tu cuenta');
INSERT INTO public.messagei18n(id,  code, locale, text)VALUES (1138,'tooltip.downloadIntaller.text','es','Descargar thunder client');
