package com.model

import com.security.User

class Object {

	String allTargets
	String name
	String imageUrl
	Integer xCordinate
	Integer yCordinate
	User creator
	User lastUpdater
	Date lastUpdated
	Date dateCreated
	GenericAction defaultAction
	Integer pType //1. WEB 2. GUI 3.CLI 4.UFT 5.RFT
	String recName
	String imageHash
	User associatedClient
	Page page
	Boolean autoGenerated 
	

	public Object(String allTargets, String name, String imageUrl,
				Integer xCordinate, Integer yCordinate, User creator,Integer pType, String recName,GenericAction defaultAction, String imageHash,User associatedClient,Page page) {
		super();
		this.allTargets = allTargets;
		this.name = name;
		this.imageUrl = imageUrl;
		this.xCordinate = xCordinate;
		this.yCordinate = yCordinate;
		this.creator = creator;
		this.lastUpdater= creator;
		this.defaultAction = defaultAction;
		this.pType = pType;
		this.recName = recName;
		this.imageHash = imageHash
		this.associatedClient = associatedClient
		this.page = page 
		this.autoGenerated = false
		
	}



		public Object(String allTargets, String name, String imageUrl,
			Integer xCordinate, Integer yCordinate, User creator,Integer pType, String recName,GenericAction defaultAction, String imageHash,User associatedClient,Page page, Boolean autoGenerated) {
		super();
		this.allTargets = allTargets;
		this.name = name;
		this.imageUrl = imageUrl;
		this.xCordinate = xCordinate;
		this.yCordinate = yCordinate;
		this.creator = creator;
		this.lastUpdater= creator;
		this.defaultAction = defaultAction;
		this.pType = pType;
		this.recName = recName;
		this.imageHash = imageHash
		this.associatedClient = associatedClient
		this.page = page
		this.autoGenerated = autoGenerated
	}





	public Object(Object object,Page page, String imageUrl,User creator){
		super();
		this.allTargets = object.allTargets;
		this.name = object.name;
		this.imageUrl = imageUrl;
		this.xCordinate = object.xCordinate;
		this.yCordinate = object.yCordinate;
		this.creator = creator;
		this.lastUpdater= creator;
		this.defaultAction = object.defaultAction;
		this.pType = object.pType;
		this.recName = object.recName;
		this.imageHash = object.imageHash
		this.associatedClient = creator.associatedClient
		this.page = page 
		this.autoGenerated = object.autoGenerated
	}


	public isValid(Integer type){
		switch(type){
			case 1:
				if(this.pType != 1 && this.pType!=2 && this.pType != 3){
					return false;
				}
				return true;
				break;
			case 2:
				if(this.pType != 2 && this.pType!=3 && this.pType != 4){
					return false;
				}
				return true;
				break;
			case 3:
				if(this.pType != 2 && this.pType!=3 && this.pType != 5){
					return false;
				}
				return true;
				break;
		}
	}

	static constraints = {
		page nullable:true
    }
	
	static mapping = {
		version false
		allTargets type:'text'
	}
}
