---


server:
    contextPath: '/app'
    #sessionTimeout: 60  #seconds
    maxPostSize: 1600000000
    maxHeaderSize: 160000000

grails:
    profile: web
    codegen:
        defaultPackage: thunder
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: false
    jmxExport: true
    driverClassName: org.postgresql.Driver
environments:
    development:
        dataSource:
            username: postgres
            password: admin123
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/THUNDERTEST
    test:
        dataSource:
            username: postgres
            password: admin123
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/THUNDERTEST
    preproduction:
        dataSource:
            username: postgres
            password: imasd
            dbCreate: update
            url: jdbc:postgresql://69.73.183.153:5432/THUNDERTEST
    production:
        dataSource:
            username: postgres
            password: 1masd2016.*_4dm1n5q
            dbCreate: update
            url: jdbc:postgresql://www.thundertest.com:5432/THUNDERTEST
